import Head from 'next/head'
// import 'styles/global.scss';
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import HomeScreen from '@/views/HomeScreen'
import { toast, ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {


  return (
    <>
      <Head>
        <title>Solana Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
       <HomeScreen/>
       <ToastContainer
          containerId="main-toast"
          theme={'dark'}
          position="bottom-right"
        />

      </main>
    </>
  )
}
